// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Google Analytics API (analytics/v3)
// Description:
//   Views and manages your Google Analytics data.
// Documentation:
//   https://developers.google.com/analytics/

#import "GTLRAnalyticsObjects.h"

// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Account
//

@implementation GTLRAnalytics_Account
@dynamic childLink, created, identifier, kind, name, permissions, selfLink,
         starred, updated;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_AccountChildLink
//

@implementation GTLRAnalytics_AccountChildLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_AccountPermissions
//

@implementation GTLRAnalytics_AccountPermissions
@dynamic effective;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"effective" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_AccountRef
//

@implementation GTLRAnalytics_AccountRef
@dynamic href, identifier, kind, name;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Accounts
//

@implementation GTLRAnalytics_Accounts
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Account class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_AccountSummaries
//

@implementation GTLRAnalytics_AccountSummaries
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_AccountSummary class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_AccountSummary
//

@implementation GTLRAnalytics_AccountSummary
@dynamic identifier, kind, name, starred, webProperties;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"webProperties" : [GTLRAnalytics_WebPropertySummary class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_AccountTicket
//

@implementation GTLRAnalytics_AccountTicket
@dynamic account, identifier, kind, profile, redirectUri, webproperty;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_AdWordsAccount
//

@implementation GTLRAnalytics_AdWordsAccount
@dynamic autoTaggingEnabled, customerId, kind;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Column
//

@implementation GTLRAnalytics_Column
@dynamic attributes, identifier, kind;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ColumnAttributes
//

@implementation GTLRAnalytics_ColumnAttributes

+ (Class)classForAdditionalProperties {
  return [NSString class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Columns
//

@implementation GTLRAnalytics_Columns
@dynamic attributeNames, ETag, items, kind, totalResults;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"ETag" : @"etag" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"attributeNames" : [NSString class],
    @"items" : [GTLRAnalytics_Column class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomDataSource
//

@implementation GTLRAnalytics_CustomDataSource
@dynamic accountId, childLink, created, descriptionProperty, identifier,
         importBehavior, kind, name, parentLink, profilesLinked, selfLink, type,
         updated, uploadType, webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"descriptionProperty" : @"description",
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"profilesLinked" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomDataSourceChildLink
//

@implementation GTLRAnalytics_CustomDataSourceChildLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomDataSourceParentLink
//

@implementation GTLRAnalytics_CustomDataSourceParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomDataSources
//

@implementation GTLRAnalytics_CustomDataSources
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_CustomDataSource class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomDimension
//

@implementation GTLRAnalytics_CustomDimension
@dynamic accountId, active, created, identifier, index, kind, name, parentLink,
         scope, selfLink, updated, webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomDimensionParentLink
//

@implementation GTLRAnalytics_CustomDimensionParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomDimensions
//

@implementation GTLRAnalytics_CustomDimensions
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_CustomDimension class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomMetric
//

@implementation GTLRAnalytics_CustomMetric
@dynamic accountId, active, created, identifier, index, kind, maxValue,
         minValue, name, parentLink, scope, selfLink, type, updated,
         webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"identifier" : @"id",
    @"maxValue" : @"max_value",
    @"minValue" : @"min_value"
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomMetricParentLink
//

@implementation GTLRAnalytics_CustomMetricParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_CustomMetrics
//

@implementation GTLRAnalytics_CustomMetrics
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_CustomMetric class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_DataimportDeleteUploadDataRequest
//

@implementation GTLRAnalytics_DataimportDeleteUploadDataRequest
@dynamic customDataImportUids;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"customDataImportUids" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_EntityAdWordsLink
//

@implementation GTLRAnalytics_EntityAdWordsLink
@dynamic adWordsAccounts, entity, identifier, kind, name, profileIds, selfLink;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"adWordsAccounts" : [GTLRAnalytics_AdWordsAccount class],
    @"profileIds" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_EntityAdWordsLinkEntity
//

@implementation GTLRAnalytics_EntityAdWordsLinkEntity
@dynamic webPropertyRef;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_EntityAdWordsLinks
//

@implementation GTLRAnalytics_EntityAdWordsLinks
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_EntityAdWordsLink class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_EntityUserLink
//

@implementation GTLRAnalytics_EntityUserLink
@dynamic entity, identifier, kind, permissions, selfLink, userRef;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_EntityUserLinkEntity
//

@implementation GTLRAnalytics_EntityUserLinkEntity
@dynamic accountRef, profileRef, webPropertyRef;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_EntityUserLinkPermissions
//

@implementation GTLRAnalytics_EntityUserLinkPermissions
@dynamic effective, local;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"effective" : [NSString class],
    @"local" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_EntityUserLinks
//

@implementation GTLRAnalytics_EntityUserLinks
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_EntityUserLink class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Experiment
//

@implementation GTLRAnalytics_Experiment
@dynamic accountId, created, descriptionProperty, editableInGaUi, endTime,
         equalWeighting, identifier, internalWebPropertyId, kind,
         minimumExperimentLengthInDays, name, objectiveMetric, optimizationType,
         parentLink, profileId, reasonExperimentEnded,
         rewriteVariationUrlsAsOriginal, selfLink, servingFramework, snippet,
         startTime, status, trafficCoverage, updated, variations, webPropertyId,
         winnerConfidenceLevel, winnerFound;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"descriptionProperty" : @"description",
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"variations" : [GTLRAnalytics_ExperimentVariationsItem class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ExperimentParentLink
//

@implementation GTLRAnalytics_ExperimentParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ExperimentVariationsItem
//

@implementation GTLRAnalytics_ExperimentVariationsItem
@dynamic name, status, url, weight, won;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Experiments
//

@implementation GTLRAnalytics_Experiments
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Experiment class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Filter
//

@implementation GTLRAnalytics_Filter
@dynamic accountId, advancedDetails, created, excludeDetails, identifier,
         includeDetails, kind, lowercaseDetails, name, parentLink,
         searchAndReplaceDetails, selfLink, type, updated, uppercaseDetails;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_FilterAdvancedDetails
//

@implementation GTLRAnalytics_FilterAdvancedDetails
@dynamic caseSensitive, extractA, extractB, fieldA, fieldAIndex, fieldARequired,
         fieldB, fieldBIndex, fieldBRequired, outputConstructor, outputToField,
         outputToFieldIndex, overrideOutputField;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_FilterLowercaseDetails
//

@implementation GTLRAnalytics_FilterLowercaseDetails
@dynamic field, fieldIndex;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_FilterParentLink
//

@implementation GTLRAnalytics_FilterParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_FilterSearchAndReplaceDetails
//

@implementation GTLRAnalytics_FilterSearchAndReplaceDetails
@dynamic caseSensitive, field, fieldIndex, replaceString, searchString;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_FilterUppercaseDetails
//

@implementation GTLRAnalytics_FilterUppercaseDetails
@dynamic field, fieldIndex;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_FilterExpression
//

@implementation GTLRAnalytics_FilterExpression
@dynamic caseSensitive, expressionValue, field, fieldIndex, kind, matchType;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_FilterRef
//

@implementation GTLRAnalytics_FilterRef
@dynamic accountId, href, identifier, kind, name;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Filters
//

@implementation GTLRAnalytics_Filters
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Filter class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaData
//

@implementation GTLRAnalytics_GaData
@dynamic columnHeaders, containsSampledData, dataLastRefreshed, dataTable,
         identifier, itemsPerPage, kind, nextLink, previousLink, profileInfo,
         query, rows, sampleSize, sampleSpace, selfLink, totalResults,
         totalsForAllResults;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"columnHeaders" : [GTLRAnalytics_GaDataColumnHeadersItem class],
    @"rows" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataColumnHeadersItem
//

@implementation GTLRAnalytics_GaDataColumnHeadersItem
@dynamic columnType, dataType, name;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataDataTable
//

@implementation GTLRAnalytics_GaDataDataTable
@dynamic cols, rows;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"cols" : [GTLRAnalytics_GaDataDataTableColsItem class],
    @"rows" : [GTLRAnalytics_GaDataDataTableRowsItem class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataProfileInfo
//

@implementation GTLRAnalytics_GaDataProfileInfo
@dynamic accountId, internalWebPropertyId, profileId, profileName, tableId,
         webPropertyId;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataQuery
//

@implementation GTLRAnalytics_GaDataQuery
@dynamic dimensions, endDate, filters, ids, maxResults, metrics, samplingLevel,
         segment, sort, startDate, startIndex;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"endDate" : @"end-date",
    @"maxResults" : @"max-results",
    @"startDate" : @"start-date",
    @"startIndex" : @"start-index"
  };
  return map;
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"metrics" : [NSString class],
    @"sort" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataTotalsForAllResults
//

@implementation GTLRAnalytics_GaDataTotalsForAllResults

+ (Class)classForAdditionalProperties {
  return [NSString class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataDataTableColsItem
//

@implementation GTLRAnalytics_GaDataDataTableColsItem
@dynamic identifier, label, type;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataDataTableRowsItem
//

@implementation GTLRAnalytics_GaDataDataTableRowsItem
@dynamic c;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"c" : [GTLRAnalytics_GaDataDataTableRowsItemCItem class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GaDataDataTableRowsItemCItem
//

@implementation GTLRAnalytics_GaDataDataTableRowsItemCItem
@dynamic v;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Goal
//

@implementation GTLRAnalytics_Goal
@dynamic accountId, active, created, eventDetails, identifier,
         internalWebPropertyId, kind, name, parentLink, profileId, selfLink,
         type, updated, urlDestinationDetails, value, visitNumPagesDetails,
         visitTimeOnSiteDetails, webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GoalEventDetails
//

@implementation GTLRAnalytics_GoalEventDetails
@dynamic eventConditions, useEventValue;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"eventConditions" : [GTLRAnalytics_GoalEventDetailsEventConditionsItem class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GoalParentLink
//

@implementation GTLRAnalytics_GoalParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GoalUrlDestinationDetails
//

@implementation GTLRAnalytics_GoalUrlDestinationDetails
@dynamic caseSensitive, firstStepRequired, matchType, steps, url;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"steps" : [GTLRAnalytics_GoalUrlDestinationDetailsStepsItem class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GoalVisitNumPagesDetails
//

@implementation GTLRAnalytics_GoalVisitNumPagesDetails
@dynamic comparisonType, comparisonValue;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GoalVisitTimeOnSiteDetails
//

@implementation GTLRAnalytics_GoalVisitTimeOnSiteDetails
@dynamic comparisonType, comparisonValue;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GoalEventDetailsEventConditionsItem
//

@implementation GTLRAnalytics_GoalEventDetailsEventConditionsItem
@dynamic comparisonType, comparisonValue, expression, matchType, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_GoalUrlDestinationDetailsStepsItem
//

@implementation GTLRAnalytics_GoalUrlDestinationDetailsStepsItem
@dynamic name, number, url;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Goals
//

@implementation GTLRAnalytics_Goals
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Goal class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_IncludeConditions
//

@implementation GTLRAnalytics_IncludeConditions
@dynamic daysToLookBack, isSmartList, kind, membershipDurationDays, segment;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_LinkedForeignAccount
//

@implementation GTLRAnalytics_LinkedForeignAccount
@dynamic accountId, eligibleForSearch, identifier, internalWebPropertyId, kind,
         linkedAccountId, remarketingAudienceId, status, type, webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_McfData
//

@implementation GTLRAnalytics_McfData
@dynamic columnHeaders, containsSampledData, identifier, itemsPerPage, kind,
         nextLink, previousLink, profileInfo, query, rows, sampleSize,
         sampleSpace, selfLink, totalResults, totalsForAllResults;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"columnHeaders" : [GTLRAnalytics_McfDataColumnHeadersItem class],
    @"rows" : [GTLRAnalytics_McfDataRowsItem class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_McfDataColumnHeadersItem
//

@implementation GTLRAnalytics_McfDataColumnHeadersItem
@dynamic columnType, dataType, name;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_McfDataProfileInfo
//

@implementation GTLRAnalytics_McfDataProfileInfo
@dynamic accountId, internalWebPropertyId, profileId, profileName, tableId,
         webPropertyId;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_McfDataQuery
//

@implementation GTLRAnalytics_McfDataQuery
@dynamic dimensions, endDate, filters, ids, maxResults, metrics, samplingLevel,
         segment, sort, startDate, startIndex;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"endDate" : @"end-date",
    @"maxResults" : @"max-results",
    @"startDate" : @"start-date",
    @"startIndex" : @"start-index"
  };
  return map;
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"metrics" : [NSString class],
    @"sort" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_McfDataRowsItem
//

@implementation GTLRAnalytics_McfDataRowsItem
@dynamic conversionPathValue, primitiveValue;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"conversionPathValue" : [GTLRAnalytics_McfDataRowsItemConversionPathValueItem class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_McfDataTotalsForAllResults
//

@implementation GTLRAnalytics_McfDataTotalsForAllResults

+ (Class)classForAdditionalProperties {
  return [NSString class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_McfDataRowsItemConversionPathValueItem
//

@implementation GTLRAnalytics_McfDataRowsItemConversionPathValueItem
@dynamic interactionType, nodeValue;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Profile
//

@implementation GTLRAnalytics_Profile
@dynamic accountId, botFilteringEnabled, childLink, created, currency,
         defaultPage, eCommerceTracking, enhancedECommerceTracking,
         excludeQueryParameters, identifier, internalWebPropertyId, kind, name,
         parentLink, permissions, selfLink, siteSearchCategoryParameters,
         siteSearchQueryParameters, starred, stripSiteSearchCategoryParameters,
         stripSiteSearchQueryParameters, timezone, type, updated, webPropertyId,
         websiteUrl;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ProfileChildLink
//

@implementation GTLRAnalytics_ProfileChildLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ProfileParentLink
//

@implementation GTLRAnalytics_ProfileParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ProfilePermissions
//

@implementation GTLRAnalytics_ProfilePermissions
@dynamic effective;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"effective" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ProfileFilterLink
//

@implementation GTLRAnalytics_ProfileFilterLink
@dynamic filterRef, identifier, kind, profileRef, rank, selfLink;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ProfileFilterLinks
//

@implementation GTLRAnalytics_ProfileFilterLinks
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_ProfileFilterLink class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ProfileRef
//

@implementation GTLRAnalytics_ProfileRef
@dynamic accountId, href, identifier, internalWebPropertyId, kind, name,
         webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Profiles
//

@implementation GTLRAnalytics_Profiles
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Profile class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_ProfileSummary
//

@implementation GTLRAnalytics_ProfileSummary
@dynamic identifier, kind, name, starred, type;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RealtimeData
//

@implementation GTLRAnalytics_RealtimeData
@dynamic columnHeaders, identifier, kind, profileInfo, query, rows, selfLink,
         totalResults, totalsForAllResults;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"columnHeaders" : [GTLRAnalytics_RealtimeDataColumnHeadersItem class],
    @"rows" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RealtimeDataColumnHeadersItem
//

@implementation GTLRAnalytics_RealtimeDataColumnHeadersItem
@dynamic columnType, dataType, name;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RealtimeDataProfileInfo
//

@implementation GTLRAnalytics_RealtimeDataProfileInfo
@dynamic accountId, internalWebPropertyId, profileId, profileName, tableId,
         webPropertyId;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RealtimeDataQuery
//

@implementation GTLRAnalytics_RealtimeDataQuery
@dynamic dimensions, filters, ids, maxResults, metrics, sort;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"maxResults" : @"max-results" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"metrics" : [NSString class],
    @"sort" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RealtimeDataTotalsForAllResults
//

@implementation GTLRAnalytics_RealtimeDataTotalsForAllResults

+ (Class)classForAdditionalProperties {
  return [NSString class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RemarketingAudience
//

@implementation GTLRAnalytics_RemarketingAudience
@dynamic accountId, audienceDefinition, audienceType, created,
         descriptionProperty, identifier, internalWebPropertyId, kind,
         linkedAdAccounts, linkedViews, name, stateBasedAudienceDefinition,
         updated, webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"descriptionProperty" : @"description",
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"linkedAdAccounts" : [GTLRAnalytics_LinkedForeignAccount class],
    @"linkedViews" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RemarketingAudienceAudienceDefinition
//

@implementation GTLRAnalytics_RemarketingAudienceAudienceDefinition
@dynamic includeConditions;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RemarketingAudienceStateBasedAudienceDefinition
//

@implementation GTLRAnalytics_RemarketingAudienceStateBasedAudienceDefinition
@dynamic excludeConditions, includeConditions;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RemarketingAudienceStateBasedAudienceDefinitionExcludeConditions
//

@implementation GTLRAnalytics_RemarketingAudienceStateBasedAudienceDefinitionExcludeConditions
@dynamic exclusionDuration, segment;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_RemarketingAudiences
//

@implementation GTLRAnalytics_RemarketingAudiences
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_RemarketingAudience class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Segment
//

@implementation GTLRAnalytics_Segment
@dynamic created, definition, identifier, kind, name, segmentId, selfLink, type,
         updated;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Segments
//

@implementation GTLRAnalytics_Segments
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Segment class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_UnsampledReport
//

@implementation GTLRAnalytics_UnsampledReport
@dynamic accountId, cloudStorageDownloadDetails, created, dimensions,
         downloadType, driveDownloadDetails, endDate, filters, identifier, kind,
         metrics, profileId, segment, selfLink, startDate, status, title,
         updated, webPropertyId;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"endDate" : @"end-date",
    @"identifier" : @"id",
    @"startDate" : @"start-date"
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_UnsampledReportCloudStorageDownloadDetails
//

@implementation GTLRAnalytics_UnsampledReportCloudStorageDownloadDetails
@dynamic bucketId, objectId;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_UnsampledReportDriveDownloadDetails
//

@implementation GTLRAnalytics_UnsampledReportDriveDownloadDetails
@dynamic documentId;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_UnsampledReports
//

@implementation GTLRAnalytics_UnsampledReports
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_UnsampledReport class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Upload
//

@implementation GTLRAnalytics_Upload
@dynamic accountId, customDataSourceId, errors, identifier, kind, status;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"errors" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Uploads
//

@implementation GTLRAnalytics_Uploads
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Upload class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_UserRef
//

@implementation GTLRAnalytics_UserRef
@dynamic email, identifier, kind;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Webproperties
//

@implementation GTLRAnalytics_Webproperties
@dynamic items, itemsPerPage, kind, nextLink, previousLink, startIndex,
         totalResults, username;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRAnalytics_Webproperty class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_Webproperty
//

@implementation GTLRAnalytics_Webproperty
@dynamic accountId, childLink, created, defaultProfileId, identifier,
         industryVertical, internalWebPropertyId, kind, level, name, parentLink,
         permissions, profileCount, selfLink, starred, updated, websiteUrl;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_WebpropertyChildLink
//

@implementation GTLRAnalytics_WebpropertyChildLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_WebpropertyParentLink
//

@implementation GTLRAnalytics_WebpropertyParentLink
@dynamic href, type;
@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_WebpropertyPermissions
//

@implementation GTLRAnalytics_WebpropertyPermissions
@dynamic effective;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"effective" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_WebPropertyRef
//

@implementation GTLRAnalytics_WebPropertyRef
@dynamic accountId, href, identifier, internalWebPropertyId, kind, name;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRAnalytics_WebPropertySummary
//

@implementation GTLRAnalytics_WebPropertySummary
@dynamic identifier, internalWebPropertyId, kind, level, name, profiles,
         starred, websiteUrl;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"profiles" : [GTLRAnalytics_ProfileSummary class]
  };
  return map;
}

@end
