language: objective-c
osx_image: xcode8.3
env:
  - TEST_TYPE=Xcode MODE=OSXCore CFG=Debug
  - TEST_TYPE=Xcode MODE=OSXCore CFG=Release
  - TEST_TYPE=Xcode MODE=iOSCore CFG=Debug
  - TEST_TYPE=Xcode MODE=iOSCore CFG=Release
  - TEST_TYPE=Xcode MODE=tvOSCore CFG=Debug
  - TEST_TYPE=Xcode MODE=tvOSCore CFG=Release
  - TEST_TYPE=Xcode MODE=watchOSCore CFG=Debug
  - TEST_TYPE=Xcode MODE=watchOSCore CFG=Release
  - TEST_TYPE=Xcode MODE=ServiceGenerator CFG=Both
  - TEST_TYPE=Xcode MODE=Example_CalendarSample CFG=Both
  - TEST_TYPE=Xcode MODE=Example_DriveSample CFG=Both
  - TEST_TYPE=Xcode MODE=Example_YouTubeSample CFG=Both
  - TEST_TYPE=Xcode MODE=Example_StorageSample CFG=Both
  - TEST_TYPE=Pod MODE=ios CFG=Debug
  - TEST_TYPE=Pod MODE=ios CFG=Release
  - TEST_TYPE=Pod MODE=osx CFG=Debug
  - TEST_TYPE=Pod MODE=osx CFG=Release
  - TEST_TYPE=Pod MODE=tvos CFG=Debug
  - TEST_TYPE=Pod MODE=tvos CFG=Release
script:
  - ./.travis.sh "${TEST_TYPE}" "${MODE}" "${CFG}"
notifications:
  email: false
