language: objective-c
osx_image: xcode8
env:
  - MODE=OSXCore CFG=Debug
  - MODE=OSXCore CFG=Release
  - MODE=iOSCore CFG=Debug
  - MODE=iOSCore CFG=Release
  - MODE=tvOSCore CFG=Debug
  - MODE=tvOSCore CFG=Release
  - MODE=ServiceGenerator CFG=Both
  - MODE=Example_CalendarSample CFG=Both
  - MODE=Example_DriveSample CFG=Both
  - MODE=Example_YouTubeSample CFG=Both
  - MODE=Example_StorageSample CFG=Both
script:
  - ./.travis.sh "${MODE}" "${CFG}"
notifications:
  email: false
