// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Web Fonts Developer API (webfonts/v1)
// Description:
//   The Google Web Fonts Developer API lets you retrieve information about web
//   fonts served
//   by Google.
// Documentation:
//   https://developers.google.com/fonts/docs/developer_api

#import "GTLRWebfonts.h"

@implementation GTLRWebfontsService

- (instancetype)init {
  self = [super init];
  if (self) {
    // From discovery.
    self.rootURLString = @"https://www.googleapis.com/";
    self.batchPath = @"batch/webfonts/v1";
    self.prettyPrintQueryParameterNames = @[ @"prettyPrint" ];
  }
  return self;
}

@end
