#!/bin/sh
#
# buildStripHeaders
#
# Remove header files from the built copy of the framework inside our
# application.

# Strip "*.h" files
find "${BUILD_ROOT}/${CONFIGURATION}/${WRAPPER_NAME}" -iname '*.h' -delete

# Strip "Headers" links
find "${BUILD_ROOT}/${CONFIGURATION}/${WRAPPER_NAME}" -iname 'Headers' -type l -delete

# Strip "Headers" directories
find "${BUILD_ROOT}/${CONFIGURATION}/${WRAPPER_NAME}" -iname 'Headers' -type d -prune -delete


