target 'CalendarSample' do
  platform :osx, '10.12'

  # Pods for GTMAppAuth development
  pod 'GoogleAPIClientForREST/Calendar', :path => '../../'
  # In production, you would use:
  # pod 'GoogleAPIClientForREST/Calendar'

  # Also use GTMAppAuth & AppAuth. See the project USING.md, you can use this or
  # Google SignIn.
  pod 'GTMAppAuth'
  pod 'AppAuth'

end
