// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Google Forms API (forms/v1)
// Description:
//   Reads and writes Google Forms and responses.
// Documentation:
//   https://developers.google.com/forms/api

#import "GTLRFormsQuery.h"

@implementation GTLRFormsQuery

@dynamic fields;

@end

@implementation GTLRFormsQuery_FormsBatchUpdate

@dynamic formId;

+ (instancetype)queryWithObject:(GTLRForms_BatchUpdateFormRequest *)object
                         formId:(NSString *)formId {
  if (object == nil) {
#if defined(DEBUG) && DEBUG
    NSAssert(object != nil, @"Got a nil object");
#endif
    return nil;
  }
  NSArray *pathParams = @[ @"formId" ];
  NSString *pathURITemplate = @"v1/forms/{formId}:batchUpdate";
  GTLRFormsQuery_FormsBatchUpdate *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.bodyObject = object;
  query.formId = formId;
  query.expectedObjectClass = [GTLRForms_BatchUpdateFormResponse class];
  query.loggingName = @"forms.forms.batchUpdate";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsCreate

+ (instancetype)queryWithObject:(GTLRForms_Form *)object {
  if (object == nil) {
#if defined(DEBUG) && DEBUG
    NSAssert(object != nil, @"Got a nil object");
#endif
    return nil;
  }
  NSString *pathURITemplate = @"v1/forms";
  GTLRFormsQuery_FormsCreate *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLRForms_Form class];
  query.loggingName = @"forms.forms.create";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsGet

@dynamic formId;

+ (instancetype)queryWithFormId:(NSString *)formId {
  NSArray *pathParams = @[ @"formId" ];
  NSString *pathURITemplate = @"v1/forms/{formId}";
  GTLRFormsQuery_FormsGet *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:pathParams];
  query.formId = formId;
  query.expectedObjectClass = [GTLRForms_Form class];
  query.loggingName = @"forms.forms.get";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsResponsesGet

@dynamic formId, responseId;

+ (instancetype)queryWithFormId:(NSString *)formId
                     responseId:(NSString *)responseId {
  NSArray *pathParams = @[
    @"formId", @"responseId"
  ];
  NSString *pathURITemplate = @"v1/forms/{formId}/responses/{responseId}";
  GTLRFormsQuery_FormsResponsesGet *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:pathParams];
  query.formId = formId;
  query.responseId = responseId;
  query.expectedObjectClass = [GTLRForms_FormResponse class];
  query.loggingName = @"forms.forms.responses.get";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsResponsesList

@dynamic filter, formId, pageSize, pageToken;

+ (instancetype)queryWithFormId:(NSString *)formId {
  NSArray *pathParams = @[ @"formId" ];
  NSString *pathURITemplate = @"v1/forms/{formId}/responses";
  GTLRFormsQuery_FormsResponsesList *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:pathParams];
  query.formId = formId;
  query.expectedObjectClass = [GTLRForms_ListFormResponsesResponse class];
  query.loggingName = @"forms.forms.responses.list";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsWatchesCreate

@dynamic formId;

+ (instancetype)queryWithObject:(GTLRForms_CreateWatchRequest *)object
                         formId:(NSString *)formId {
  if (object == nil) {
#if defined(DEBUG) && DEBUG
    NSAssert(object != nil, @"Got a nil object");
#endif
    return nil;
  }
  NSArray *pathParams = @[ @"formId" ];
  NSString *pathURITemplate = @"v1/forms/{formId}/watches";
  GTLRFormsQuery_FormsWatchesCreate *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.bodyObject = object;
  query.formId = formId;
  query.expectedObjectClass = [GTLRForms_Watch class];
  query.loggingName = @"forms.forms.watches.create";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsWatchesDelete

@dynamic formId, watchId;

+ (instancetype)queryWithFormId:(NSString *)formId
                        watchId:(NSString *)watchId {
  NSArray *pathParams = @[
    @"formId", @"watchId"
  ];
  NSString *pathURITemplate = @"v1/forms/{formId}/watches/{watchId}";
  GTLRFormsQuery_FormsWatchesDelete *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"DELETE"
                       pathParameterNames:pathParams];
  query.formId = formId;
  query.watchId = watchId;
  query.expectedObjectClass = [GTLRForms_Empty class];
  query.loggingName = @"forms.forms.watches.delete";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsWatchesList

@dynamic formId;

+ (instancetype)queryWithFormId:(NSString *)formId {
  NSArray *pathParams = @[ @"formId" ];
  NSString *pathURITemplate = @"v1/forms/{formId}/watches";
  GTLRFormsQuery_FormsWatchesList *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:pathParams];
  query.formId = formId;
  query.expectedObjectClass = [GTLRForms_ListWatchesResponse class];
  query.loggingName = @"forms.forms.watches.list";
  return query;
}

@end

@implementation GTLRFormsQuery_FormsWatchesRenew

@dynamic formId, watchId;

+ (instancetype)queryWithObject:(GTLRForms_RenewWatchRequest *)object
                         formId:(NSString *)formId
                        watchId:(NSString *)watchId {
  if (object == nil) {
#if defined(DEBUG) && DEBUG
    NSAssert(object != nil, @"Got a nil object");
#endif
    return nil;
  }
  NSArray *pathParams = @[
    @"formId", @"watchId"
  ];
  NSString *pathURITemplate = @"v1/forms/{formId}/watches/{watchId}:renew";
  GTLRFormsQuery_FormsWatchesRenew *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.bodyObject = object;
  query.formId = formId;
  query.watchId = watchId;
  query.expectedObjectClass = [GTLRForms_Watch class];
  query.loggingName = @"forms.forms.watches.renew";
  return query;
}

@end
