target 'StorageSample' do
  platform :osx, '10.12'

  # GTMAppAuth is now written in Swift, so need this to build.
  use_frameworks!

  pod 'GoogleAPIClientForREST/Storage', :path => '../../'
  # In production, you would use:
  # pod 'GoogleAPIClientForREST/Storage'

  # Also use GTMAppAuth & AppAuth. See the project USING.md, you can use this or
  # Google SignIn.
  pod 'GTMAppAuth', '>= 3.0'
  pod 'AppAuth'

end
