// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Google Play Game Services Management API (gamesManagement/v1management)
// Description:
//   The Management API for Google Play Game Services.
// Documentation:
//   https://developers.google.com/games/services

#import "GTLRGamesManagementQuery.h"

#import "GTLRGamesManagementObjects.h"

@implementation GTLRGamesManagementQuery

@dynamic fields;

@end

@implementation GTLRGamesManagementQuery_AchievementsReset

@dynamic achievementId;

+ (instancetype)queryWithAchievementId:(NSString *)achievementId {
  NSArray *pathParams = @[ @"achievementId" ];
  NSString *pathURITemplate = @"achievements/{achievementId}/reset";
  GTLRGamesManagementQuery_AchievementsReset *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.achievementId = achievementId;
  query.expectedObjectClass = [GTLRGamesManagement_AchievementResetResponse class];
  query.loggingName = @"gamesManagement.achievements.reset";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_AchievementsResetAll

+ (instancetype)query {
  NSString *pathURITemplate = @"achievements/reset";
  GTLRGamesManagementQuery_AchievementsResetAll *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.expectedObjectClass = [GTLRGamesManagement_AchievementResetAllResponse class];
  query.loggingName = @"gamesManagement.achievements.resetAll";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_AchievementsResetAllForAllPlayers

+ (instancetype)query {
  NSString *pathURITemplate = @"achievements/resetAllForAllPlayers";
  GTLRGamesManagementQuery_AchievementsResetAllForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.achievements.resetAllForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_AchievementsResetForAllPlayers

@dynamic achievementId;

+ (instancetype)queryWithAchievementId:(NSString *)achievementId {
  NSArray *pathParams = @[ @"achievementId" ];
  NSString *pathURITemplate = @"achievements/{achievementId}/resetForAllPlayers";
  GTLRGamesManagementQuery_AchievementsResetForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.achievementId = achievementId;
  query.loggingName = @"gamesManagement.achievements.resetForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_AchievementsResetMultipleForAllPlayers

+ (instancetype)queryWithObject:(GTLRGamesManagement_AchievementResetMultipleForAllRequest *)object {
  if (object == nil) {
    GTLR_DEBUG_ASSERT(object != nil, @"Got a nil object");
    return nil;
  }
  NSString *pathURITemplate = @"achievements/resetMultipleForAllPlayers";
  GTLRGamesManagementQuery_AchievementsResetMultipleForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.bodyObject = object;
  query.loggingName = @"gamesManagement.achievements.resetMultipleForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_ApplicationsListHidden

@dynamic applicationId, maxResults, pageToken;

+ (instancetype)queryWithApplicationId:(NSString *)applicationId {
  NSArray *pathParams = @[ @"applicationId" ];
  NSString *pathURITemplate = @"applications/{applicationId}/players/hidden";
  GTLRGamesManagementQuery_ApplicationsListHidden *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:pathParams];
  query.applicationId = applicationId;
  query.expectedObjectClass = [GTLRGamesManagement_HiddenPlayerList class];
  query.loggingName = @"gamesManagement.applications.listHidden";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_EventsReset

@dynamic eventId;

+ (instancetype)queryWithEventId:(NSString *)eventId {
  NSArray *pathParams = @[ @"eventId" ];
  NSString *pathURITemplate = @"events/{eventId}/reset";
  GTLRGamesManagementQuery_EventsReset *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.eventId = eventId;
  query.loggingName = @"gamesManagement.events.reset";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_EventsResetAll

+ (instancetype)query {
  NSString *pathURITemplate = @"events/reset";
  GTLRGamesManagementQuery_EventsResetAll *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.events.resetAll";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_EventsResetAllForAllPlayers

+ (instancetype)query {
  NSString *pathURITemplate = @"events/resetAllForAllPlayers";
  GTLRGamesManagementQuery_EventsResetAllForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.events.resetAllForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_EventsResetForAllPlayers

@dynamic eventId;

+ (instancetype)queryWithEventId:(NSString *)eventId {
  NSArray *pathParams = @[ @"eventId" ];
  NSString *pathURITemplate = @"events/{eventId}/resetForAllPlayers";
  GTLRGamesManagementQuery_EventsResetForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.eventId = eventId;
  query.loggingName = @"gamesManagement.events.resetForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_EventsResetMultipleForAllPlayers

+ (instancetype)queryWithObject:(GTLRGamesManagement_EventsResetMultipleForAllRequest *)object {
  if (object == nil) {
    GTLR_DEBUG_ASSERT(object != nil, @"Got a nil object");
    return nil;
  }
  NSString *pathURITemplate = @"events/resetMultipleForAllPlayers";
  GTLRGamesManagementQuery_EventsResetMultipleForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.bodyObject = object;
  query.loggingName = @"gamesManagement.events.resetMultipleForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_PlayersHide

@dynamic applicationId, playerId;

+ (instancetype)queryWithApplicationId:(NSString *)applicationId
                              playerId:(NSString *)playerId {
  NSArray *pathParams = @[
    @"applicationId", @"playerId"
  ];
  NSString *pathURITemplate = @"applications/{applicationId}/players/hidden/{playerId}";
  GTLRGamesManagementQuery_PlayersHide *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.applicationId = applicationId;
  query.playerId = playerId;
  query.loggingName = @"gamesManagement.players.hide";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_PlayersUnhide

@dynamic applicationId, playerId;

+ (instancetype)queryWithApplicationId:(NSString *)applicationId
                              playerId:(NSString *)playerId {
  NSArray *pathParams = @[
    @"applicationId", @"playerId"
  ];
  NSString *pathURITemplate = @"applications/{applicationId}/players/hidden/{playerId}";
  GTLRGamesManagementQuery_PlayersUnhide *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"DELETE"
                       pathParameterNames:pathParams];
  query.applicationId = applicationId;
  query.playerId = playerId;
  query.loggingName = @"gamesManagement.players.unhide";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_QuestsReset

@dynamic questId;

+ (instancetype)queryWithQuestId:(NSString *)questId {
  NSArray *pathParams = @[ @"questId" ];
  NSString *pathURITemplate = @"quests/{questId}/reset";
  GTLRGamesManagementQuery_QuestsReset *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.questId = questId;
  query.loggingName = @"gamesManagement.quests.reset";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_QuestsResetAll

+ (instancetype)query {
  NSString *pathURITemplate = @"quests/reset";
  GTLRGamesManagementQuery_QuestsResetAll *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.quests.resetAll";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_QuestsResetAllForAllPlayers

+ (instancetype)query {
  NSString *pathURITemplate = @"quests/resetAllForAllPlayers";
  GTLRGamesManagementQuery_QuestsResetAllForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.quests.resetAllForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_QuestsResetForAllPlayers

@dynamic questId;

+ (instancetype)queryWithQuestId:(NSString *)questId {
  NSArray *pathParams = @[ @"questId" ];
  NSString *pathURITemplate = @"quests/{questId}/resetForAllPlayers";
  GTLRGamesManagementQuery_QuestsResetForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.questId = questId;
  query.loggingName = @"gamesManagement.quests.resetForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_QuestsResetMultipleForAllPlayers

+ (instancetype)queryWithObject:(GTLRGamesManagement_QuestsResetMultipleForAllRequest *)object {
  if (object == nil) {
    GTLR_DEBUG_ASSERT(object != nil, @"Got a nil object");
    return nil;
  }
  NSString *pathURITemplate = @"quests/resetMultipleForAllPlayers";
  GTLRGamesManagementQuery_QuestsResetMultipleForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.bodyObject = object;
  query.loggingName = @"gamesManagement.quests.resetMultipleForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_RoomsReset

+ (instancetype)query {
  NSString *pathURITemplate = @"rooms/reset";
  GTLRGamesManagementQuery_RoomsReset *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.rooms.reset";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_RoomsResetForAllPlayers

+ (instancetype)query {
  NSString *pathURITemplate = @"rooms/resetForAllPlayers";
  GTLRGamesManagementQuery_RoomsResetForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.rooms.resetForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_ScoresReset

@dynamic leaderboardId;

+ (instancetype)queryWithLeaderboardId:(NSString *)leaderboardId {
  NSArray *pathParams = @[ @"leaderboardId" ];
  NSString *pathURITemplate = @"leaderboards/{leaderboardId}/scores/reset";
  GTLRGamesManagementQuery_ScoresReset *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.leaderboardId = leaderboardId;
  query.expectedObjectClass = [GTLRGamesManagement_PlayerScoreResetResponse class];
  query.loggingName = @"gamesManagement.scores.reset";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_ScoresResetAll

+ (instancetype)query {
  NSString *pathURITemplate = @"scores/reset";
  GTLRGamesManagementQuery_ScoresResetAll *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.expectedObjectClass = [GTLRGamesManagement_PlayerScoreResetAllResponse class];
  query.loggingName = @"gamesManagement.scores.resetAll";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_ScoresResetAllForAllPlayers

+ (instancetype)query {
  NSString *pathURITemplate = @"scores/resetAllForAllPlayers";
  GTLRGamesManagementQuery_ScoresResetAllForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.scores.resetAllForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_ScoresResetForAllPlayers

@dynamic leaderboardId;

+ (instancetype)queryWithLeaderboardId:(NSString *)leaderboardId {
  NSArray *pathParams = @[ @"leaderboardId" ];
  NSString *pathURITemplate = @"leaderboards/{leaderboardId}/scores/resetForAllPlayers";
  GTLRGamesManagementQuery_ScoresResetForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:pathParams];
  query.leaderboardId = leaderboardId;
  query.loggingName = @"gamesManagement.scores.resetForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_ScoresResetMultipleForAllPlayers

+ (instancetype)queryWithObject:(GTLRGamesManagement_ScoresResetMultipleForAllRequest *)object {
  if (object == nil) {
    GTLR_DEBUG_ASSERT(object != nil, @"Got a nil object");
    return nil;
  }
  NSString *pathURITemplate = @"scores/resetMultipleForAllPlayers";
  GTLRGamesManagementQuery_ScoresResetMultipleForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.bodyObject = object;
  query.loggingName = @"gamesManagement.scores.resetMultipleForAllPlayers";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_TurnBasedMatchesReset

+ (instancetype)query {
  NSString *pathURITemplate = @"turnbasedmatches/reset";
  GTLRGamesManagementQuery_TurnBasedMatchesReset *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.turnBasedMatches.reset";
  return query;
}

@end

@implementation GTLRGamesManagementQuery_TurnBasedMatchesResetForAllPlayers

+ (instancetype)query {
  NSString *pathURITemplate = @"turnbasedmatches/resetForAllPlayers";
  GTLRGamesManagementQuery_TurnBasedMatchesResetForAllPlayers *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.loggingName = @"gamesManagement.turnBasedMatches.resetForAllPlayers";
  return query;
}

@end
