// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   GDC Virtual API (gkeonprem/v1)
// Documentation:
//   https://cloud.google.com/anthos/clusters/docs/on-prem/

#import "GTLRGKEOnPremObjects.h"
#import "GTLRGKEOnPremQuery.h"
#import "GTLRGKEOnPremService.h"
