target 'DriveSample' do
  platform :osx, '10.12'

  pod 'GoogleAPIClientForREST/Drive', :path => '../../'
  # In production, you would use:
  # pod 'GoogleAPIClientForREST/Drive'

  # Also use GTMAppAuth & AppAuth. See the project USING.md, you can use this or
  # Google SignIn.
  pod 'GTMAppAuth'
  pod 'AppAuth'

end
