// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   KMS Inventory API (kmsinventory/v1)
// Documentation:
//   https://cloud.google.com/kms/

#import <GoogleAPIClientForREST/GTLRKmsinventoryObjects.h>

// ----------------------------------------------------------------------------
// Constants

// GTLRKmsinventory_GoogleCloudKmsV1CryptoKey.purpose
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Purpose_AsymmetricDecrypt = @"ASYMMETRIC_DECRYPT";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Purpose_AsymmetricSign = @"ASYMMETRIC_SIGN";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Purpose_CryptoKeyPurposeUnspecified = @"CRYPTO_KEY_PURPOSE_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Purpose_EncryptDecrypt = @"ENCRYPT_DECRYPT";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Purpose_KeyEncapsulation = @"KEY_ENCAPSULATION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Purpose_Mac = @"MAC";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Purpose_RawEncryptDecrypt = @"RAW_ENCRYPT_DECRYPT";

// GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion.algorithm
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_Aes128Cbc = @"AES_128_CBC";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_Aes128Ctr = @"AES_128_CTR";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_Aes128Gcm = @"AES_128_GCM";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_Aes256Cbc = @"AES_256_CBC";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_Aes256Ctr = @"AES_256_CTR";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_Aes256Gcm = @"AES_256_GCM";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_CryptoKeyVersionAlgorithmUnspecified = @"CRYPTO_KEY_VERSION_ALGORITHM_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_EcSignEd25519 = @"EC_SIGN_ED25519";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_EcSignP256Sha256 = @"EC_SIGN_P256_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_EcSignP384Sha384 = @"EC_SIGN_P384_SHA384";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_EcSignSecp256k1Sha256 = @"EC_SIGN_SECP256K1_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_ExternalSymmetricEncryption = @"EXTERNAL_SYMMETRIC_ENCRYPTION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_GoogleSymmetricEncryption = @"GOOGLE_SYMMETRIC_ENCRYPTION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_HmacSha1 = @"HMAC_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_HmacSha224 = @"HMAC_SHA224";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_HmacSha256 = @"HMAC_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_HmacSha384 = @"HMAC_SHA384";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_HmacSha512 = @"HMAC_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_KemXwing = @"KEM_XWING";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_MlKem1024 = @"ML_KEM_1024";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_MlKem768 = @"ML_KEM_768";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_PqSignHashSlhDsaSha2128sSha256 = @"PQ_SIGN_HASH_SLH_DSA_SHA2_128S_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_PqSignMlDsa44 = @"PQ_SIGN_ML_DSA_44";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_PqSignMlDsa65 = @"PQ_SIGN_ML_DSA_65";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_PqSignMlDsa87 = @"PQ_SIGN_ML_DSA_87";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_PqSignSlhDsaSha2128s = @"PQ_SIGN_SLH_DSA_SHA2_128S";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaDecryptOaep2048Sha1 = @"RSA_DECRYPT_OAEP_2048_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaDecryptOaep2048Sha256 = @"RSA_DECRYPT_OAEP_2048_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaDecryptOaep3072Sha1 = @"RSA_DECRYPT_OAEP_3072_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaDecryptOaep3072Sha256 = @"RSA_DECRYPT_OAEP_3072_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaDecryptOaep4096Sha1 = @"RSA_DECRYPT_OAEP_4096_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaDecryptOaep4096Sha256 = @"RSA_DECRYPT_OAEP_4096_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaDecryptOaep4096Sha512 = @"RSA_DECRYPT_OAEP_4096_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPkcs12048Sha256 = @"RSA_SIGN_PKCS1_2048_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPkcs13072Sha256 = @"RSA_SIGN_PKCS1_3072_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPkcs14096Sha256 = @"RSA_SIGN_PKCS1_4096_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPkcs14096Sha512 = @"RSA_SIGN_PKCS1_4096_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPss2048Sha256 = @"RSA_SIGN_PSS_2048_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPss3072Sha256 = @"RSA_SIGN_PSS_3072_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPss4096Sha256 = @"RSA_SIGN_PSS_4096_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignPss4096Sha512 = @"RSA_SIGN_PSS_4096_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignRawPkcs12048 = @"RSA_SIGN_RAW_PKCS1_2048";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignRawPkcs13072 = @"RSA_SIGN_RAW_PKCS1_3072";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_Algorithm_RsaSignRawPkcs14096 = @"RSA_SIGN_RAW_PKCS1_4096";

// GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion.protectionLevel
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_ProtectionLevel_External = @"EXTERNAL";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_ProtectionLevel_ExternalVpc = @"EXTERNAL_VPC";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_ProtectionLevel_Hsm = @"HSM";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_ProtectionLevel_ProtectionLevelUnspecified = @"PROTECTION_LEVEL_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_ProtectionLevel_Software = @"SOFTWARE";

// GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion.state
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_CryptoKeyVersionStateUnspecified = @"CRYPTO_KEY_VERSION_STATE_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_Destroyed = @"DESTROYED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_DestroyScheduled = @"DESTROY_SCHEDULED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_Disabled = @"DISABLED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_Enabled = @"ENABLED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_ExternalDestructionFailed = @"EXTERNAL_DESTRUCTION_FAILED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_GenerationFailed = @"GENERATION_FAILED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_ImportFailed = @"IMPORT_FAILED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_PendingExternalDestruction = @"PENDING_EXTERNAL_DESTRUCTION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_PendingGeneration = @"PENDING_GENERATION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion_State_PendingImport = @"PENDING_IMPORT";

// GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate.algorithm
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_Aes128Cbc = @"AES_128_CBC";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_Aes128Ctr = @"AES_128_CTR";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_Aes128Gcm = @"AES_128_GCM";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_Aes256Cbc = @"AES_256_CBC";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_Aes256Ctr = @"AES_256_CTR";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_Aes256Gcm = @"AES_256_GCM";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_CryptoKeyVersionAlgorithmUnspecified = @"CRYPTO_KEY_VERSION_ALGORITHM_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_EcSignEd25519 = @"EC_SIGN_ED25519";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_EcSignP256Sha256 = @"EC_SIGN_P256_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_EcSignP384Sha384 = @"EC_SIGN_P384_SHA384";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_EcSignSecp256k1Sha256 = @"EC_SIGN_SECP256K1_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_ExternalSymmetricEncryption = @"EXTERNAL_SYMMETRIC_ENCRYPTION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_GoogleSymmetricEncryption = @"GOOGLE_SYMMETRIC_ENCRYPTION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_HmacSha1 = @"HMAC_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_HmacSha224 = @"HMAC_SHA224";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_HmacSha256 = @"HMAC_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_HmacSha384 = @"HMAC_SHA384";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_HmacSha512 = @"HMAC_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_KemXwing = @"KEM_XWING";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_MlKem1024 = @"ML_KEM_1024";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_MlKem768 = @"ML_KEM_768";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_PqSignHashSlhDsaSha2128sSha256 = @"PQ_SIGN_HASH_SLH_DSA_SHA2_128S_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_PqSignMlDsa44 = @"PQ_SIGN_ML_DSA_44";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_PqSignMlDsa65 = @"PQ_SIGN_ML_DSA_65";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_PqSignMlDsa87 = @"PQ_SIGN_ML_DSA_87";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_PqSignSlhDsaSha2128s = @"PQ_SIGN_SLH_DSA_SHA2_128S";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaDecryptOaep2048Sha1 = @"RSA_DECRYPT_OAEP_2048_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaDecryptOaep2048Sha256 = @"RSA_DECRYPT_OAEP_2048_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaDecryptOaep3072Sha1 = @"RSA_DECRYPT_OAEP_3072_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaDecryptOaep3072Sha256 = @"RSA_DECRYPT_OAEP_3072_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaDecryptOaep4096Sha1 = @"RSA_DECRYPT_OAEP_4096_SHA1";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaDecryptOaep4096Sha256 = @"RSA_DECRYPT_OAEP_4096_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaDecryptOaep4096Sha512 = @"RSA_DECRYPT_OAEP_4096_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPkcs12048Sha256 = @"RSA_SIGN_PKCS1_2048_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPkcs13072Sha256 = @"RSA_SIGN_PKCS1_3072_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPkcs14096Sha256 = @"RSA_SIGN_PKCS1_4096_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPkcs14096Sha512 = @"RSA_SIGN_PKCS1_4096_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPss2048Sha256 = @"RSA_SIGN_PSS_2048_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPss3072Sha256 = @"RSA_SIGN_PSS_3072_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPss4096Sha256 = @"RSA_SIGN_PSS_4096_SHA256";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignPss4096Sha512 = @"RSA_SIGN_PSS_4096_SHA512";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignRawPkcs12048 = @"RSA_SIGN_RAW_PKCS1_2048";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignRawPkcs13072 = @"RSA_SIGN_RAW_PKCS1_3072";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_Algorithm_RsaSignRawPkcs14096 = @"RSA_SIGN_RAW_PKCS1_4096";

// GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate.protectionLevel
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_ProtectionLevel_External = @"EXTERNAL";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_ProtectionLevel_ExternalVpc = @"EXTERNAL_VPC";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_ProtectionLevel_Hsm = @"HSM";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_ProtectionLevel_ProtectionLevelUnspecified = @"PROTECTION_LEVEL_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate_ProtectionLevel_Software = @"SOFTWARE";

// GTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy.allowedAccessReasons
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_CustomerAuthorizedWorkflowServicing = @"CUSTOMER_AUTHORIZED_WORKFLOW_SERVICING";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_CustomerInitiatedAccess = @"CUSTOMER_INITIATED_ACCESS";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_CustomerInitiatedSupport = @"CUSTOMER_INITIATED_SUPPORT";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_GoogleInitiatedReview = @"GOOGLE_INITIATED_REVIEW";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_GoogleInitiatedService = @"GOOGLE_INITIATED_SERVICE";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_GoogleInitiatedSystemOperation = @"GOOGLE_INITIATED_SYSTEM_OPERATION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_GoogleResponseToProductionAlert = @"GOOGLE_RESPONSE_TO_PRODUCTION_ALERT";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_ModifiedCustomerInitiatedAccess = @"MODIFIED_CUSTOMER_INITIATED_ACCESS";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_ModifiedGoogleInitiatedSystemOperation = @"MODIFIED_GOOGLE_INITIATED_SYSTEM_OPERATION";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_ReasonNotExpected = @"REASON_NOT_EXPECTED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_ReasonUnspecified = @"REASON_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy_AllowedAccessReasons_ThirdPartyDataRequest = @"THIRD_PARTY_DATA_REQUEST";

// GTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestation.format
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestation_Format_AttestationFormatUnspecified = @"ATTESTATION_FORMAT_UNSPECIFIED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestation_Format_CaviumV1Compressed = @"CAVIUM_V1_COMPRESSED";
NSString * const kGTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestation_Format_CaviumV2Compressed = @"CAVIUM_V2_COMPRESSED";

// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1ListCryptoKeysResponse
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1ListCryptoKeysResponse
@dynamic cryptoKeys, nextPageToken;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"cryptoKeys" : [GTLRKmsinventory_GoogleCloudKmsV1CryptoKey class]
  };
  return map;
}

+ (NSString *)collectionItemsKey {
  return @"cryptoKeys";
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResource
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResource
@dynamic cloudProduct, createTime, cryptoKeyVersion, cryptoKeyVersions, labels,
         location, name, project, projectId, resourceType;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"cryptoKeyVersions" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResource_Labels
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResource_Labels

+ (Class)classForAdditionalProperties {
  return [NSString class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary
@dynamic cloudProducts, locations, name, projectCount, resourceCount,
         resourceTypes;
@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary_CloudProducts
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary_CloudProducts

+ (Class)classForAdditionalProperties {
  return [NSNumber class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary_Locations
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary_Locations

+ (Class)classForAdditionalProperties {
  return [NSNumber class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary_ResourceTypes
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResourcesSummary_ResourceTypes

+ (Class)classForAdditionalProperties {
  return [NSNumber class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsInventoryV1SearchProtectedResourcesResponse
//

@implementation GTLRKmsinventory_GoogleCloudKmsInventoryV1SearchProtectedResourcesResponse
@dynamic nextPageToken, protectedResources;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"protectedResources" : [GTLRKmsinventory_GoogleCloudKmsInventoryV1ProtectedResource class]
  };
  return map;
}

+ (NSString *)collectionItemsKey {
  return @"protectedResources";
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1CryptoKey
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1CryptoKey
@dynamic createTime, cryptoKeyBackend, destroyScheduledDuration, importOnly,
         keyAccessJustificationsPolicy, labels, name, nextRotationTime, primary,
         purpose, rotationPeriod, versionTemplate;
@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Labels
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1CryptoKey_Labels

+ (Class)classForAdditionalProperties {
  return [NSString class];
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersion
@dynamic algorithm, attestation, createTime, destroyEventTime, destroyTime,
         externalDestructionFailureReason, externalProtectionLevelOptions,
         generateTime, generationFailureReason, importFailureReason, importJob,
         importTime, name, protectionLevel, reimportEligible, state;
@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1CryptoKeyVersionTemplate
@dynamic algorithm, protectionLevel;
@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1ExternalProtectionLevelOptions
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1ExternalProtectionLevelOptions
@dynamic ekmConnectionKeyPath, externalKeyUri;
@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1KeyAccessJustificationsPolicy
@dynamic allowedAccessReasons;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"allowedAccessReasons" : [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestation
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestation
@dynamic certChains, content, format;
@end


// ----------------------------------------------------------------------------
//
//   GTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestationCertificateChains
//

@implementation GTLRKmsinventory_GoogleCloudKmsV1KeyOperationAttestationCertificateChains
@dynamic caviumCerts, googleCardCerts, googlePartitionCerts;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"caviumCerts" : [NSString class],
    @"googleCardCerts" : [NSString class],
    @"googlePartitionCerts" : [NSString class]
  };
  return map;
}

@end
