// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Real-time Bidding API (realtimebidding/v1)
// Description:
//   Allows external bidders to manage their RTB integration with Google. This
//   includes managing bidder endpoints, QPS quotas, configuring what ad
//   inventory to receive with pretargeting, submitting creatives for
//   verification, and accessing creative metadata such as approval status.
// Documentation:
//   https://developers.google.com/authorized-buyers/apis/realtimebidding/reference/rest/

#import <GoogleAPIClientForREST/GTLRQuery.h>

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

#import "GTLRRealTimeBiddingObjects.h"

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the query classes' properties below.

// ----------------------------------------------------------------------------
// view

/**
 *  Not specified, equivalent to SERVING_DECISION_ONLY.
 *
 *  Value: "CREATIVE_VIEW_UNSPECIFIED"
 */
FOUNDATION_EXTERN NSString * const kGTLRRealTimeBiddingViewCreativeViewUnspecified;
/**
 *  The entire creative resource (including the declared fields and the creative
 *  content) is included in the response.
 *
 *  Value: "FULL"
 */
FOUNDATION_EXTERN NSString * const kGTLRRealTimeBiddingViewFull;
/**
 *  Only creativeServingDecision is included in the response.
 *
 *  Value: "SERVING_DECISION_ONLY"
 */
FOUNDATION_EXTERN NSString * const kGTLRRealTimeBiddingViewServingDecisionOnly;

// ----------------------------------------------------------------------------
// Query Classes
//

/**
 *  Parent class for other Real-time Bidding query classes.
 */
@interface GTLRRealTimeBiddingQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  Lists creatives as they are at the time of the initial request. This call
 *  may take multiple hours to complete. For large, paginated requests, this
 *  method returns a snapshot of creatives at the time of request for the first
 *  page. `lastStatusUpdate` and `creativeServingDecision` may be outdated for
 *  creatives on sequential pages. We recommend [Google Cloud
 *  Pub/Sub](//cloud.google.com/pubsub/docs/overview) to view the latest status.
 *
 *  Method: realtimebidding.bidders.creatives.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersCreativesList : GTLRRealTimeBiddingQuery

/**
 *  Query string to filter creatives. If no filter is specified, all active
 *  creatives will be returned. Example: 'accountId=12345 AND
 *  (dealsStatus:DISAPPROVED AND disapprovalReason:UNACCEPTABLE_CONTENT) OR
 *  declaredAttributes:IS_COOKIE_TARGETED'
 */
@property(nonatomic, copy, nullable) NSString *filter;

/**
 *  Requested page size. The server may return fewer creatives than requested
 *  (due to timeout constraint) even if more are available through another call.
 *  If unspecified, server will pick an appropriate default. Acceptable values
 *  are 1 to 1000, inclusive.
 */
@property(nonatomic, assign) NSInteger pageSize;

/**
 *  A token identifying a page of results the server should return. Typically,
 *  this is the value of ListCreativesResponse.nextPageToken returned from the
 *  previous call to the 'ListCreatives' method. Page tokens for continued pages
 *  are valid for up to five hours, counting from the call to 'ListCreatives'
 *  for the first page.
 */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Required. Name of the parent buyer that owns the creatives. The pattern for
 *  this resource is either `buyers/{buyerAccountId}` or
 *  `bidders/{bidderAccountId}`. For `buyers/{buyerAccountId}`, the
 *  `buyerAccountId` can be one of the following: 1. The ID of the buyer that is
 *  accessing their own creatives. 2. The ID of the child seat buyer under a
 *  bidder account. So for listing creatives pertaining to the child seat buyer
 *  (`456`) under bidder account (`123`), you would use the pattern:
 *  `buyers/456`. 3. The ID of the bidder itself. So for listing creatives
 *  pertaining to bidder (`123`), you would use `buyers/123`. If you want to
 *  access all creatives pertaining to both the bidder and all of its child seat
 *  accounts, you would use `bidders/{bidderAccountId}`, for example, for all
 *  creatives pertaining to bidder (`123`), use `bidders/123`.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Controls the amount of information included in the response. By default only
 *  creativeServingDecision is included. To retrieve the entire creative
 *  resource (including the declared fields and the creative content) specify
 *  the view as "FULL".
 *
 *  Likely values:
 *    @arg @c kGTLRRealTimeBiddingViewCreativeViewUnspecified Not specified,
 *        equivalent to SERVING_DECISION_ONLY. (Value:
 *        "CREATIVE_VIEW_UNSPECIFIED")
 *    @arg @c kGTLRRealTimeBiddingViewServingDecisionOnly Only
 *        creativeServingDecision is included in the response. (Value:
 *        "SERVING_DECISION_ONLY")
 *    @arg @c kGTLRRealTimeBiddingViewFull The entire creative resource
 *        (including the declared fields and the creative content) is included
 *        in the response. (Value: "FULL")
 */
@property(nonatomic, copy, nullable) NSString *view;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListCreativesResponse.
 *
 *  Lists creatives as they are at the time of the initial request. This call
 *  may take multiple hours to complete. For large, paginated requests, this
 *  method returns a snapshot of creatives at the time of request for the first
 *  page. `lastStatusUpdate` and `creativeServingDecision` may be outdated for
 *  creatives on sequential pages. We recommend [Google Cloud
 *  Pub/Sub](//cloud.google.com/pubsub/docs/overview) to view the latest status.
 *
 *  @param parent Required. Name of the parent buyer that owns the creatives.
 *    The pattern for this resource is either `buyers/{buyerAccountId}` or
 *    `bidders/{bidderAccountId}`. For `buyers/{buyerAccountId}`, the
 *    `buyerAccountId` can be one of the following: 1. The ID of the buyer that
 *    is accessing their own creatives. 2. The ID of the child seat buyer under
 *    a bidder account. So for listing creatives pertaining to the child seat
 *    buyer (`456`) under bidder account (`123`), you would use the pattern:
 *    `buyers/456`. 3. The ID of the bidder itself. So for listing creatives
 *    pertaining to bidder (`123`), you would use `buyers/123`. If you want to
 *    access all creatives pertaining to both the bidder and all of its child
 *    seat accounts, you would use `bidders/{bidderAccountId}`, for example, for
 *    all creatives pertaining to bidder (`123`), use `bidders/123`.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersCreativesList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)queryWithParent:(NSString *)parent;

@end

/**
 *  Watches all creatives pertaining to a bidder. It is sufficient to invoke
 *  this endpoint once per bidder. A Pub/Sub topic will be created and
 *  notifications will be pushed to the topic when any of the bidder's creatives
 *  change status. All of the bidder's service accounts will have access to read
 *  from the topic. Subsequent invocations of this method will return the
 *  existing Pub/Sub configuration.
 *
 *  Method: realtimebidding.bidders.creatives.watch
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersCreativesWatch : GTLRRealTimeBiddingQuery

/**
 *  Required. To watch all creatives pertaining to the bidder and all its child
 *  seat accounts, the bidder must follow the pattern
 *  `bidders/{bidderAccountId}`.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_WatchCreativesResponse.
 *
 *  Watches all creatives pertaining to a bidder. It is sufficient to invoke
 *  this endpoint once per bidder. A Pub/Sub topic will be created and
 *  notifications will be pushed to the topic when any of the bidder's creatives
 *  change status. All of the bidder's service accounts will have access to read
 *  from the topic. Subsequent invocations of this method will return the
 *  existing Pub/Sub configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_WatchCreativesRequest to include in
 *    the query.
 *  @param parent Required. To watch all creatives pertaining to the bidder and
 *    all its child seat accounts, the bidder must follow the pattern
 *    `bidders/{bidderAccountId}`.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersCreativesWatch
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_WatchCreativesRequest *)object
                         parent:(NSString *)parent;

@end

/**
 *  Gets a bidder endpoint by its name.
 *
 *  Method: realtimebidding.bidders.endpoints.get
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersEndpointsGet : GTLRRealTimeBiddingQuery

/**
 *  Required. Name of the bidder endpoint to get. Format:
 *  `bidders/{bidderAccountId}/endpoints/{endpointId}`
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_Endpoint.
 *
 *  Gets a bidder endpoint by its name.
 *
 *  @param name Required. Name of the bidder endpoint to get. Format:
 *    `bidders/{bidderAccountId}/endpoints/{endpointId}`
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersEndpointsGet
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Lists all the bidder's endpoints.
 *
 *  Method: realtimebidding.bidders.endpoints.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersEndpointsList : GTLRRealTimeBiddingQuery

/**
 *  The maximum number of endpoints to return. If unspecified, at most 100
 *  endpoints will be returned. The maximum value is 500; values above 500 will
 *  be coerced to 500.
 */
@property(nonatomic, assign) NSInteger pageSize;

/**
 *  A token identifying a page of results the server should return. This value
 *  is received from a previous `ListEndpoints` call in
 *  ListEndpointsResponse.nextPageToken.
 */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Required. Name of the bidder whose endpoints will be listed. Format:
 *  `bidders/{bidderAccountId}`
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListEndpointsResponse.
 *
 *  Lists all the bidder's endpoints.
 *
 *  @param parent Required. Name of the bidder whose endpoints will be listed.
 *    Format: `bidders/{bidderAccountId}`
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersEndpointsList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)queryWithParent:(NSString *)parent;

@end

/**
 *  Updates a bidder's endpoint.
 *
 *  Method: realtimebidding.bidders.endpoints.patch
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersEndpointsPatch : GTLRRealTimeBiddingQuery

/**
 *  Output only. Name of the endpoint resource that must follow the pattern
 *  `bidders/{bidderAccountId}/endpoints/{endpointId}`, where {bidderAccountId}
 *  is the account ID of the bidder who operates this endpoint, and {endpointId}
 *  is a unique ID assigned by the server.
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Field mask to use for partial in-place updates.
 *
 *  String format is a comma-separated list of fields.
 */
@property(nonatomic, copy, nullable) NSString *updateMask;

/**
 *  Fetches a @c GTLRRealTimeBidding_Endpoint.
 *
 *  Updates a bidder's endpoint.
 *
 *  @param object The @c GTLRRealTimeBidding_Endpoint to include in the query.
 *  @param name Output only. Name of the endpoint resource that must follow the
 *    pattern `bidders/{bidderAccountId}/endpoints/{endpointId}`, where
 *    {bidderAccountId} is the account ID of the bidder who operates this
 *    endpoint, and {endpointId} is a unique ID assigned by the server.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersEndpointsPatch
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_Endpoint *)object
                           name:(NSString *)name;

@end

/**
 *  Gets a bidder account by its name.
 *
 *  Method: realtimebidding.bidders.get
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersGet : GTLRRealTimeBiddingQuery

/**
 *  Required. Name of the bidder to get. Format: `bidders/{bidderAccountId}`
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_Bidder.
 *
 *  Gets a bidder account by its name.
 *
 *  @param name Required. Name of the bidder to get. Format:
 *    `bidders/{bidderAccountId}`
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersGet
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Lists all the bidder accounts that belong to the caller.
 *
 *  Method: realtimebidding.bidders.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersList : GTLRRealTimeBiddingQuery

/**
 *  The maximum number of bidders to return. If unspecified, at most 100 bidders
 *  will be returned. The maximum value is 500; values above 500 will be coerced
 *  to 500.
 */
@property(nonatomic, assign) NSInteger pageSize;

/**
 *  A token identifying a page of results the server should return. This value
 *  is received from a previous `ListBidders` call in
 *  ListBiddersResponse.nextPageToken.
 */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListBiddersResponse.
 *
 *  Lists all the bidder accounts that belong to the caller.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)query;

@end

/**
 *  Activates a pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.activate
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsActivate : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Activates a pretargeting configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_ActivatePretargetingConfigRequest
 *    to include in the query.
 *  @param name Required. The name of the pretargeting configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsActivate
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_ActivatePretargetingConfigRequest *)object
                           name:(NSString *)name;

@end

/**
 *  Adds targeted apps to the pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.addTargetedApps
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsAddTargetedApps : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *pretargetingConfig;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Adds targeted apps to the pretargeting configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_AddTargetedAppsRequest to include
 *    in the query.
 *  @param pretargetingConfig Required. The name of the pretargeting
 *    configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsAddTargetedApps
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_AddTargetedAppsRequest *)object
             pretargetingConfig:(NSString *)pretargetingConfig;

@end

/**
 *  Adds targeted publishers to the pretargeting config.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.addTargetedPublishers
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsAddTargetedPublishers : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *pretargetingConfig;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Adds targeted publishers to the pretargeting config.
 *
 *  @param object The @c GTLRRealTimeBidding_AddTargetedPublishersRequest to
 *    include in the query.
 *  @param pretargetingConfig Required. The name of the pretargeting
 *    configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsAddTargetedPublishers
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_AddTargetedPublishersRequest *)object
             pretargetingConfig:(NSString *)pretargetingConfig;

@end

/**
 *  Adds targeted sites to the pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.addTargetedSites
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsAddTargetedSites : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *pretargetingConfig;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Adds targeted sites to the pretargeting configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_AddTargetedSitesRequest to include
 *    in the query.
 *  @param pretargetingConfig Required. The name of the pretargeting
 *    configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsAddTargetedSites
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_AddTargetedSitesRequest *)object
             pretargetingConfig:(NSString *)pretargetingConfig;

@end

/**
 *  Creates a pretargeting configuration. A pretargeting configuration's state
 *  (PretargetingConfig.state) is active upon creation, and it will start to
 *  affect traffic shortly after. A bidder may create a maximum of 10
 *  pretargeting configurations. Attempts to exceed this maximum results in a
 *  400 bad request error.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.create
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsCreate : GTLRRealTimeBiddingQuery

/**
 *  Required. Name of the bidder to create the pretargeting configuration for.
 *  Format: bidders/{bidderAccountId}
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Creates a pretargeting configuration. A pretargeting configuration's state
 *  (PretargetingConfig.state) is active upon creation, and it will start to
 *  affect traffic shortly after. A bidder may create a maximum of 10
 *  pretargeting configurations. Attempts to exceed this maximum results in a
 *  400 bad request error.
 *
 *  @param object The @c GTLRRealTimeBidding_PretargetingConfig to include in
 *    the query.
 *  @param parent Required. Name of the bidder to create the pretargeting
 *    configuration for. Format: bidders/{bidderAccountId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsCreate
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_PretargetingConfig *)object
                         parent:(NSString *)parent;

@end

/**
 *  Deletes a pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.delete
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsDelete : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration to delete. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_Empty.
 *
 *  Deletes a pretargeting configuration.
 *
 *  @param name Required. The name of the pretargeting configuration to delete.
 *    Format: bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsDelete
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Gets a pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.get
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsGet : GTLRRealTimeBiddingQuery

/**
 *  Required. Name of the pretargeting configuration to get. Format:
 *  bidders/{bidderAccountId}/pretargetingConfigs/{configId}
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Gets a pretargeting configuration.
 *
 *  @param name Required. Name of the pretargeting configuration to get. Format:
 *    bidders/{bidderAccountId}/pretargetingConfigs/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsGet
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Lists all pretargeting configurations for a single bidder.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsList : GTLRRealTimeBiddingQuery

/**
 *  The maximum number of pretargeting configurations to return. If unspecified,
 *  at most 10 pretargeting configurations will be returned. The maximum value
 *  is 100; values above 100 will be coerced to 100.
 */
@property(nonatomic, assign) NSInteger pageSize;

/**
 *  A token identifying a page of results the server should return. This value
 *  is received from a previous `ListPretargetingConfigs` call in
 *  ListPretargetingConfigsResponse.nextPageToken.
 */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Required. Name of the bidder whose pretargeting configurations will be
 *  listed. Format: bidders/{bidderAccountId}
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListPretargetingConfigsResponse.
 *
 *  Lists all pretargeting configurations for a single bidder.
 *
 *  @param parent Required. Name of the bidder whose pretargeting configurations
 *    will be listed. Format: bidders/{bidderAccountId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)queryWithParent:(NSString *)parent;

@end

/**
 *  Updates a pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.patch
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsPatch : GTLRRealTimeBiddingQuery

/**
 *  Output only. Name of the pretargeting configuration that must follow the
 *  pattern `bidders/{bidder_account_id}/pretargetingConfigs/{config_id}`
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Field mask to use for partial in-place updates.
 *
 *  String format is a comma-separated list of fields.
 */
@property(nonatomic, copy, nullable) NSString *updateMask;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Updates a pretargeting configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_PretargetingConfig to include in
 *    the query.
 *  @param name Output only. Name of the pretargeting configuration that must
 *    follow the pattern
 *    `bidders/{bidder_account_id}/pretargetingConfigs/{config_id}`
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsPatch
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_PretargetingConfig *)object
                           name:(NSString *)name;

@end

/**
 *  Removes targeted apps from the pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.removeTargetedApps
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsRemoveTargetedApps : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *pretargetingConfig;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Removes targeted apps from the pretargeting configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_RemoveTargetedAppsRequest to
 *    include in the query.
 *  @param pretargetingConfig Required. The name of the pretargeting
 *    configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsRemoveTargetedApps
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_RemoveTargetedAppsRequest *)object
             pretargetingConfig:(NSString *)pretargetingConfig;

@end

/**
 *  Removes targeted publishers from the pretargeting config.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.removeTargetedPublishers
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsRemoveTargetedPublishers : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *pretargetingConfig;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Removes targeted publishers from the pretargeting config.
 *
 *  @param object The @c GTLRRealTimeBidding_RemoveTargetedPublishersRequest to
 *    include in the query.
 *  @param pretargetingConfig Required. The name of the pretargeting
 *    configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsRemoveTargetedPublishers
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_RemoveTargetedPublishersRequest *)object
             pretargetingConfig:(NSString *)pretargetingConfig;

@end

/**
 *  Removes targeted sites from the pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.removeTargetedSites
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsRemoveTargetedSites : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *pretargetingConfig;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Removes targeted sites from the pretargeting configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_RemoveTargetedSitesRequest to
 *    include in the query.
 *  @param pretargetingConfig Required. The name of the pretargeting
 *    configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsRemoveTargetedSites
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_RemoveTargetedSitesRequest *)object
             pretargetingConfig:(NSString *)pretargetingConfig;

@end

/**
 *  Suspends a pretargeting configuration.
 *
 *  Method: realtimebidding.bidders.pretargetingConfigs.suspend
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsSuspend : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the pretargeting configuration. Format:
 *  bidders/{bidderAccountId}/pretargetingConfig/{configId}
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_PretargetingConfig.
 *
 *  Suspends a pretargeting configuration.
 *
 *  @param object The @c GTLRRealTimeBidding_SuspendPretargetingConfigRequest to
 *    include in the query.
 *  @param name Required. The name of the pretargeting configuration. Format:
 *    bidders/{bidderAccountId}/pretargetingConfig/{configId}
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPretargetingConfigsSuspend
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_SuspendPretargetingConfigRequest *)object
                           name:(NSString *)name;

@end

/**
 *  Batch approves multiple publisher connections.
 *
 *  Method: realtimebidding.bidders.publisherConnections.batchApprove
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsBatchApprove : GTLRRealTimeBiddingQuery

/**
 *  Required. The bidder for whom publisher connections will be approved.
 *  Format: `bidders/{bidder}` where `{bidder}` is the account ID of the bidder.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_BatchApprovePublisherConnectionsResponse.
 *
 *  Batch approves multiple publisher connections.
 *
 *  @param object The @c
 *    GTLRRealTimeBidding_BatchApprovePublisherConnectionsRequest to include in
 *    the query.
 *  @param parent Required. The bidder for whom publisher connections will be
 *    approved. Format: `bidders/{bidder}` where `{bidder}` is the account ID of
 *    the bidder.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsBatchApprove
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_BatchApprovePublisherConnectionsRequest *)object
                         parent:(NSString *)parent;

@end

/**
 *  Batch rejects multiple publisher connections.
 *
 *  Method: realtimebidding.bidders.publisherConnections.batchReject
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsBatchReject : GTLRRealTimeBiddingQuery

/**
 *  Required. The bidder for whom publisher connections will be rejected.
 *  Format: `bidders/{bidder}` where `{bidder}` is the account ID of the bidder.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_BatchRejectPublisherConnectionsResponse.
 *
 *  Batch rejects multiple publisher connections.
 *
 *  @param object The @c
 *    GTLRRealTimeBidding_BatchRejectPublisherConnectionsRequest to include in
 *    the query.
 *  @param parent Required. The bidder for whom publisher connections will be
 *    rejected. Format: `bidders/{bidder}` where `{bidder}` is the account ID of
 *    the bidder.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsBatchReject
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_BatchRejectPublisherConnectionsRequest *)object
                         parent:(NSString *)parent;

@end

/**
 *  Gets a publisher connection.
 *
 *  Method: realtimebidding.bidders.publisherConnections.get
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsGet : GTLRRealTimeBiddingQuery

/**
 *  Required. Name of the publisher whose connection information is to be
 *  retrieved. In the pattern
 *  `bidders/{bidder}/publisherConnections/{publisher}` where `{bidder}` is the
 *  account ID of the bidder, and `{publisher}` is the ads.txt/app-ads.txt
 *  publisher ID. See publisherConnection.name.
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_PublisherConnection.
 *
 *  Gets a publisher connection.
 *
 *  @param name Required. Name of the publisher whose connection information is
 *    to be retrieved. In the pattern
 *    `bidders/{bidder}/publisherConnections/{publisher}` where `{bidder}` is
 *    the account ID of the bidder, and `{publisher}` is the ads.txt/app-ads.txt
 *    publisher ID. See publisherConnection.name.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsGet
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Lists publisher connections for a given bidder.
 *
 *  Method: realtimebidding.bidders.publisherConnections.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsList : GTLRRealTimeBiddingQuery

/**
 *  Query string to filter publisher connections. Connections can be filtered by
 *  `displayName`, `publisherPlatform`, and `biddingState`. If no filter is
 *  specified, all publisher connections will be returned. Example:
 *  'displayName="Great Publisher*" AND publisherPlatform=ADMOB AND biddingState
 *  != PENDING' See https://google.aip.dev/160 for more information about
 *  filtering syntax.
 */
@property(nonatomic, copy, nullable) NSString *filter;

/**
 *  Order specification by which results should be sorted. If no sort order is
 *  specified, the results will be returned in alphabetic order based on the
 *  publisher's publisher code. Results can be sorted by `createTime`. Example:
 *  'createTime DESC'.
 */
@property(nonatomic, copy, nullable) NSString *orderBy;

/**
 *  Requested page size. The server may return fewer results than requested (due
 *  to timeout constraint) even if more are available through another call. If
 *  unspecified, the server will pick an appropriate default. Acceptable values
 *  are 1 to 5000, inclusive.
 */
@property(nonatomic, assign) NSInteger pageSize;

/**
 *  A token identifying a page of results the server should return. Typically,
 *  this is the value of ListPublisherConnectionsResponse.nextPageToken returned
 *  from the previous call to the 'ListPublisherConnections' method.
 */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Required. Name of the bidder for which publishers have initiated
 *  connections. The pattern for this resource is `bidders/{bidder}` where
 *  `{bidder}` represents the account ID of the bidder.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListPublisherConnectionsResponse.
 *
 *  Lists publisher connections for a given bidder.
 *
 *  @param parent Required. Name of the bidder for which publishers have
 *    initiated connections. The pattern for this resource is `bidders/{bidder}`
 *    where `{bidder}` represents the account ID of the bidder.
 *
 *  @return GTLRRealTimeBiddingQuery_BiddersPublisherConnectionsList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)queryWithParent:(NSString *)parent;

@end

/**
 *  Creates a creative.
 *
 *  Method: realtimebidding.buyers.creatives.create
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersCreativesCreate : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the parent buyer that the new creative belongs to that
 *  must follow the pattern `buyers/{buyerAccountId}`, where `{buyerAccountId}`
 *  represents the account ID of the buyer who owns a creative. For a bidder
 *  accessing creatives on behalf of a child seat buyer, `{buyerAccountId}`
 *  should represent the account ID of the child seat buyer.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_Creative.
 *
 *  Creates a creative.
 *
 *  @param object The @c GTLRRealTimeBidding_Creative to include in the query.
 *  @param parent Required. The name of the parent buyer that the new creative
 *    belongs to that must follow the pattern `buyers/{buyerAccountId}`, where
 *    `{buyerAccountId}` represents the account ID of the buyer who owns a
 *    creative. For a bidder accessing creatives on behalf of a child seat
 *    buyer, `{buyerAccountId}` should represent the account ID of the child
 *    seat buyer.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersCreativesCreate
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_Creative *)object
                         parent:(NSString *)parent;

@end

/**
 *  Gets a creative.
 *
 *  Method: realtimebidding.buyers.creatives.get
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersCreativesGet : GTLRRealTimeBiddingQuery

/** Required. Name of the creative to retrieve. See creative.name. */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Controls the amount of information included in the response. By default only
 *  creativeServingDecision is included. To retrieve the entire creative
 *  resource (including the declared fields and the creative content) specify
 *  the view as "FULL".
 *
 *  Likely values:
 *    @arg @c kGTLRRealTimeBiddingViewCreativeViewUnspecified Not specified,
 *        equivalent to SERVING_DECISION_ONLY. (Value:
 *        "CREATIVE_VIEW_UNSPECIFIED")
 *    @arg @c kGTLRRealTimeBiddingViewServingDecisionOnly Only
 *        creativeServingDecision is included in the response. (Value:
 *        "SERVING_DECISION_ONLY")
 *    @arg @c kGTLRRealTimeBiddingViewFull The entire creative resource
 *        (including the declared fields and the creative content) is included
 *        in the response. (Value: "FULL")
 */
@property(nonatomic, copy, nullable) NSString *view;

/**
 *  Fetches a @c GTLRRealTimeBidding_Creative.
 *
 *  Gets a creative.
 *
 *  @param name Required. Name of the creative to retrieve. See creative.name.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersCreativesGet
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Lists creatives as they are at the time of the initial request. This call
 *  may take multiple hours to complete. For large, paginated requests, this
 *  method returns a snapshot of creatives at the time of request for the first
 *  page. `lastStatusUpdate` and `creativeServingDecision` may be outdated for
 *  creatives on sequential pages. We recommend [Google Cloud
 *  Pub/Sub](//cloud.google.com/pubsub/docs/overview) to view the latest status.
 *
 *  Method: realtimebidding.buyers.creatives.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersCreativesList : GTLRRealTimeBiddingQuery

/**
 *  Query string to filter creatives. If no filter is specified, all active
 *  creatives will be returned. Example: 'accountId=12345 AND
 *  (dealsStatus:DISAPPROVED AND disapprovalReason:UNACCEPTABLE_CONTENT) OR
 *  declaredAttributes:IS_COOKIE_TARGETED'
 */
@property(nonatomic, copy, nullable) NSString *filter;

/**
 *  Requested page size. The server may return fewer creatives than requested
 *  (due to timeout constraint) even if more are available through another call.
 *  If unspecified, server will pick an appropriate default. Acceptable values
 *  are 1 to 1000, inclusive.
 */
@property(nonatomic, assign) NSInteger pageSize;

/**
 *  A token identifying a page of results the server should return. Typically,
 *  this is the value of ListCreativesResponse.nextPageToken returned from the
 *  previous call to the 'ListCreatives' method. Page tokens for continued pages
 *  are valid for up to five hours, counting from the call to 'ListCreatives'
 *  for the first page.
 */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Required. Name of the parent buyer that owns the creatives. The pattern for
 *  this resource is either `buyers/{buyerAccountId}` or
 *  `bidders/{bidderAccountId}`. For `buyers/{buyerAccountId}`, the
 *  `buyerAccountId` can be one of the following: 1. The ID of the buyer that is
 *  accessing their own creatives. 2. The ID of the child seat buyer under a
 *  bidder account. So for listing creatives pertaining to the child seat buyer
 *  (`456`) under bidder account (`123`), you would use the pattern:
 *  `buyers/456`. 3. The ID of the bidder itself. So for listing creatives
 *  pertaining to bidder (`123`), you would use `buyers/123`. If you want to
 *  access all creatives pertaining to both the bidder and all of its child seat
 *  accounts, you would use `bidders/{bidderAccountId}`, for example, for all
 *  creatives pertaining to bidder (`123`), use `bidders/123`.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Controls the amount of information included in the response. By default only
 *  creativeServingDecision is included. To retrieve the entire creative
 *  resource (including the declared fields and the creative content) specify
 *  the view as "FULL".
 *
 *  Likely values:
 *    @arg @c kGTLRRealTimeBiddingViewCreativeViewUnspecified Not specified,
 *        equivalent to SERVING_DECISION_ONLY. (Value:
 *        "CREATIVE_VIEW_UNSPECIFIED")
 *    @arg @c kGTLRRealTimeBiddingViewServingDecisionOnly Only
 *        creativeServingDecision is included in the response. (Value:
 *        "SERVING_DECISION_ONLY")
 *    @arg @c kGTLRRealTimeBiddingViewFull The entire creative resource
 *        (including the declared fields and the creative content) is included
 *        in the response. (Value: "FULL")
 */
@property(nonatomic, copy, nullable) NSString *view;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListCreativesResponse.
 *
 *  Lists creatives as they are at the time of the initial request. This call
 *  may take multiple hours to complete. For large, paginated requests, this
 *  method returns a snapshot of creatives at the time of request for the first
 *  page. `lastStatusUpdate` and `creativeServingDecision` may be outdated for
 *  creatives on sequential pages. We recommend [Google Cloud
 *  Pub/Sub](//cloud.google.com/pubsub/docs/overview) to view the latest status.
 *
 *  @param parent Required. Name of the parent buyer that owns the creatives.
 *    The pattern for this resource is either `buyers/{buyerAccountId}` or
 *    `bidders/{bidderAccountId}`. For `buyers/{buyerAccountId}`, the
 *    `buyerAccountId` can be one of the following: 1. The ID of the buyer that
 *    is accessing their own creatives. 2. The ID of the child seat buyer under
 *    a bidder account. So for listing creatives pertaining to the child seat
 *    buyer (`456`) under bidder account (`123`), you would use the pattern:
 *    `buyers/456`. 3. The ID of the bidder itself. So for listing creatives
 *    pertaining to bidder (`123`), you would use `buyers/123`. If you want to
 *    access all creatives pertaining to both the bidder and all of its child
 *    seat accounts, you would use `bidders/{bidderAccountId}`, for example, for
 *    all creatives pertaining to bidder (`123`), use `bidders/123`.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersCreativesList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)queryWithParent:(NSString *)parent;

@end

/**
 *  Updates a creative.
 *
 *  Method: realtimebidding.buyers.creatives.patch
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersCreativesPatch : GTLRRealTimeBiddingQuery

/**
 *  Output only. Name of the creative. Follows the pattern
 *  `buyers/{buyer}/creatives/{creative}`, where `{buyer}` represents the
 *  account ID of the buyer who owns the creative, and `{creative}` is the
 *  buyer-specific creative ID that references this creative in the bid
 *  response.
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Field mask to use for partial in-place updates.
 *
 *  String format is a comma-separated list of fields.
 */
@property(nonatomic, copy, nullable) NSString *updateMask;

/**
 *  Fetches a @c GTLRRealTimeBidding_Creative.
 *
 *  Updates a creative.
 *
 *  @param object The @c GTLRRealTimeBidding_Creative to include in the query.
 *  @param name Output only. Name of the creative. Follows the pattern
 *    `buyers/{buyer}/creatives/{creative}`, where `{buyer}` represents the
 *    account ID of the buyer who owns the creative, and `{creative}` is the
 *    buyer-specific creative ID that references this creative in the bid
 *    response.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersCreativesPatch
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_Creative *)object
                           name:(NSString *)name;

@end

/**
 *  Gets a buyer account by its name.
 *
 *  Method: realtimebidding.buyers.get
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersGet : GTLRRealTimeBiddingQuery

/** Required. Name of the buyer to get. Format: `buyers/{buyerId}` */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_Buyer.
 *
 *  Gets a buyer account by its name.
 *
 *  @param name Required. Name of the buyer to get. Format: `buyers/{buyerId}`
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersGet
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  This has been sunset as of October 2023, and will return an error response
 *  if called. For more information, see the release notes:
 *  https://developers.google.com/authorized-buyers/apis/relnotes#real-time-bidding-api
 *  Gets remarketing tag for a buyer. A remarketing tag is a piece of JavaScript
 *  code that can be placed on a web page. When a user visits a page containing
 *  a remarketing tag, Google adds the user to a user list.
 *
 *  Method: realtimebidding.buyers.getRemarketingTag
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersGetRemarketingTag : GTLRRealTimeBiddingQuery

/**
 *  Required. To fetch the remarketing tag for an account, the name must follow
 *  the pattern `buyers/{accountId}`, where `{accountId}` represents the ID of
 *  the buyer that owns the remarketing tag. For a bidder accessing the
 *  remarketing tag on behalf of a child seat buyer, `{accountId}` should
 *  represent the ID of the child seat buyer. To fetch the remarketing tag for a
 *  specific user list, the name must follow the pattern
 *  `buyers/{accountId}/userLists/{userListId}`. See UserList.name.
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_GetRemarketingTagResponse.
 *
 *  This has been sunset as of October 2023, and will return an error response
 *  if called. For more information, see the release notes:
 *  https://developers.google.com/authorized-buyers/apis/relnotes#real-time-bidding-api
 *  Gets remarketing tag for a buyer. A remarketing tag is a piece of JavaScript
 *  code that can be placed on a web page. When a user visits a page containing
 *  a remarketing tag, Google adds the user to a user list.
 *
 *  @param name Required. To fetch the remarketing tag for an account, the name
 *    must follow the pattern `buyers/{accountId}`, where `{accountId}`
 *    represents the ID of the buyer that owns the remarketing tag. For a bidder
 *    accessing the remarketing tag on behalf of a child seat buyer,
 *    `{accountId}` should represent the ID of the child seat buyer. To fetch
 *    the remarketing tag for a specific user list, the name must follow the
 *    pattern `buyers/{accountId}/userLists/{userListId}`. See UserList.name.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersGetRemarketingTag
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Lists all buyer account information the calling buyer user or service
 *  account is permissioned to manage.
 *
 *  Method: realtimebidding.buyers.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersList : GTLRRealTimeBiddingQuery

/**
 *  The maximum number of buyers to return. If unspecified, at most 100 buyers
 *  will be returned. The maximum value is 500; values above 500 will be coerced
 *  to 500.
 */
@property(nonatomic, assign) NSInteger pageSize;

/**
 *  A token identifying a page of results the server should return. This value
 *  is received from a previous `ListBuyers` call in
 *  ListBuyersResponse.nextPageToken.
 */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListBuyersResponse.
 *
 *  Lists all buyer account information the calling buyer user or service
 *  account is permissioned to manage.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)query;

@end

/**
 *  Changes the status of a user list to CLOSED. This prevents new users from
 *  being added to the user list.
 *
 *  Method: realtimebidding.buyers.userLists.close
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersUserListsClose : GTLRRealTimeBiddingQuery

/** Required. The name of the user list to close. See UserList.name */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_UserList.
 *
 *  Changes the status of a user list to CLOSED. This prevents new users from
 *  being added to the user list.
 *
 *  @param object The @c GTLRRealTimeBidding_CloseUserListRequest to include in
 *    the query.
 *  @param name Required. The name of the user list to close. See UserList.name
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersUserListsClose
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_CloseUserListRequest *)object
                           name:(NSString *)name;

@end

/**
 *  Creates a new user list.
 *
 *  Method: realtimebidding.buyers.userLists.create
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersUserListsCreate : GTLRRealTimeBiddingQuery

/**
 *  Required. The name of the parent buyer of the user list to be retrieved,
 *  which must follow the pattern `buyers/{buyerAccountId}`, where
 *  `{buyerAccountId}` represents the account ID of the buyer who owns the user
 *  list. For a bidder accessing user lists on behalf of a child seat buyer,
 *  `{buyerAccountId}` should represent the account ID of the child seat buyer.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_UserList.
 *
 *  Creates a new user list.
 *
 *  @param object The @c GTLRRealTimeBidding_UserList to include in the query.
 *  @param parent Required. The name of the parent buyer of the user list to be
 *    retrieved, which must follow the pattern `buyers/{buyerAccountId}`, where
 *    `{buyerAccountId}` represents the account ID of the buyer who owns the
 *    user list. For a bidder accessing user lists on behalf of a child seat
 *    buyer, `{buyerAccountId}` should represent the account ID of the child
 *    seat buyer.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersUserListsCreate
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_UserList *)object
                         parent:(NSString *)parent;

@end

/**
 *  Gets a user list by its name.
 *
 *  Method: realtimebidding.buyers.userLists.get
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersUserListsGet : GTLRRealTimeBiddingQuery

/** Required. The name of the user list to be retrieved. See UserList.name. */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_UserList.
 *
 *  Gets a user list by its name.
 *
 *  @param name Required. The name of the user list to be retrieved. See
 *    UserList.name.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersUserListsGet
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  This has been sunset as of October 2023, and will return an error response
 *  if called. For more information, see the release notes:
 *  https://developers.google.com/authorized-buyers/apis/relnotes#real-time-bidding-api
 *  Gets remarketing tag for a buyer. A remarketing tag is a piece of JavaScript
 *  code that can be placed on a web page. When a user visits a page containing
 *  a remarketing tag, Google adds the user to a user list.
 *
 *  Method: realtimebidding.buyers.userLists.getRemarketingTag
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersUserListsGetRemarketingTag : GTLRRealTimeBiddingQuery

/**
 *  Required. To fetch the remarketing tag for an account, the name must follow
 *  the pattern `buyers/{accountId}`, where `{accountId}` represents the ID of
 *  the buyer that owns the remarketing tag. For a bidder accessing the
 *  remarketing tag on behalf of a child seat buyer, `{accountId}` should
 *  represent the ID of the child seat buyer. To fetch the remarketing tag for a
 *  specific user list, the name must follow the pattern
 *  `buyers/{accountId}/userLists/{userListId}`. See UserList.name.
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_GetRemarketingTagResponse.
 *
 *  This has been sunset as of October 2023, and will return an error response
 *  if called. For more information, see the release notes:
 *  https://developers.google.com/authorized-buyers/apis/relnotes#real-time-bidding-api
 *  Gets remarketing tag for a buyer. A remarketing tag is a piece of JavaScript
 *  code that can be placed on a web page. When a user visits a page containing
 *  a remarketing tag, Google adds the user to a user list.
 *
 *  @param name Required. To fetch the remarketing tag for an account, the name
 *    must follow the pattern `buyers/{accountId}`, where `{accountId}`
 *    represents the ID of the buyer that owns the remarketing tag. For a bidder
 *    accessing the remarketing tag on behalf of a child seat buyer,
 *    `{accountId}` should represent the ID of the child seat buyer. To fetch
 *    the remarketing tag for a specific user list, the name must follow the
 *    pattern `buyers/{accountId}/userLists/{userListId}`. See UserList.name.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersUserListsGetRemarketingTag
 */
+ (instancetype)queryWithName:(NSString *)name;

@end

/**
 *  Lists the user lists visible to the current user.
 *
 *  Method: realtimebidding.buyers.userLists.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersUserListsList : GTLRRealTimeBiddingQuery

/** The number of results to return per page. */
@property(nonatomic, assign) NSInteger pageSize;

/** Continuation page token as received from a previous response. */
@property(nonatomic, copy, nullable) NSString *pageToken;

/**
 *  Required. The name of the parent buyer for the user lists to be returned
 *  that must follow the pattern `buyers/{buyerAccountId}`, where
 *  `{buyerAccountId}` represents the account ID of the buyer who owns user
 *  lists. For a bidder accessing user lists on behalf of a child seat buyer ,
 *  `{buyerAccountId}` should represent the account ID of the child seat buyer.
 */
@property(nonatomic, copy, nullable) NSString *parent;

/**
 *  Fetches a @c GTLRRealTimeBidding_ListUserListsResponse.
 *
 *  Lists the user lists visible to the current user.
 *
 *  @param parent Required. The name of the parent buyer for the user lists to
 *    be returned that must follow the pattern `buyers/{buyerAccountId}`, where
 *    `{buyerAccountId}` represents the account ID of the buyer who owns user
 *    lists. For a bidder accessing user lists on behalf of a child seat buyer ,
 *    `{buyerAccountId}` should represent the account ID of the child seat
 *    buyer.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersUserListsList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)queryWithParent:(NSString *)parent;

@end

/**
 *  Changes the status of a user list to OPEN. This allows new users to be added
 *  to the user list.
 *
 *  Method: realtimebidding.buyers.userLists.open
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersUserListsOpen : GTLRRealTimeBiddingQuery

/** Required. The name of the user list to open. See UserList.name */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_UserList.
 *
 *  Changes the status of a user list to OPEN. This allows new users to be added
 *  to the user list.
 *
 *  @param object The @c GTLRRealTimeBidding_OpenUserListRequest to include in
 *    the query.
 *  @param name Required. The name of the user list to open. See UserList.name
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersUserListsOpen
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_OpenUserListRequest *)object
                           name:(NSString *)name;

@end

/**
 *  Updates the given user list. Only user lists with URLRestrictions can be
 *  updated.
 *
 *  Method: realtimebidding.buyers.userLists.update
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeRealTimeBiddingRealtimeBidding
 */
@interface GTLRRealTimeBiddingQuery_BuyersUserListsUpdate : GTLRRealTimeBiddingQuery

/**
 *  Output only. Name of the user list that must follow the pattern
 *  `buyers/{buyer}/userLists/{user_list}`, where `{buyer}` represents the
 *  account ID of the buyer who owns the user list. For a bidder accessing user
 *  lists on behalf of a child seat buyer, `{buyer}` represents the account ID
 *  of the child seat buyer. `{user_list}` is an int64 identifier assigned by
 *  Google to uniquely identify a user list.
 */
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  Fetches a @c GTLRRealTimeBidding_UserList.
 *
 *  Updates the given user list. Only user lists with URLRestrictions can be
 *  updated.
 *
 *  @param object The @c GTLRRealTimeBidding_UserList to include in the query.
 *  @param name Output only. Name of the user list that must follow the pattern
 *    `buyers/{buyer}/userLists/{user_list}`, where `{buyer}` represents the
 *    account ID of the buyer who owns the user list. For a bidder accessing
 *    user lists on behalf of a child seat buyer, `{buyer}` represents the
 *    account ID of the child seat buyer. `{user_list}` is an int64 identifier
 *    assigned by Google to uniquely identify a user list.
 *
 *  @return GTLRRealTimeBiddingQuery_BuyersUserListsUpdate
 */
+ (instancetype)queryWithObject:(GTLRRealTimeBidding_UserList *)object
                           name:(NSString *)name;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
