name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'LICENSE'
    - '*.podspec'
    - '**/Package*.swift'
    - '.github/workflows/cocoapods.yml'
    - '.github/workflows/swiftpm.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'LICENSE'
    - '*.podspec'
    - '**/Package*.swift'
    - '.github/workflows/cocoapods.yml'
    - '.github/workflows/swiftpm.yml'

jobs:
  xcode:
    name: Xcode
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        MODE: ["OSXCore", "iOSCore", "tvOSCore", "watchOSCore"]
        CFG: ["Debug", "Release"]
        include:
        - MODE: "ServiceGenerator"
          CFG: "Both"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: True
    - name: Build and Test
      run:  Tests/xcode_tests.sh ${{ matrix.MODE }} ${{ matrix.CFG }}
